Trying to build for asus merlin router
No success yet though..

Need to solve this:
ext/libpcap/libpcap.a(pcap-linux.c.o): In function `pcap_create_interface':
pcap-linux.c:(.text+0x190): undefined reference to `eventfd'